#!/usr/bin/env python3
import argparse
import csv
import re
import statistics
from pathlib import Path


NAME_RE = re.compile(r"^mul-(?P<mul>.+)_modmul-(?P<modmul>.+)_rsa-(?P<rsa>.+)\.log$")
PROFILE_NAME_RE = re.compile(
    r"^mul-(?P<mul>.+)_modmul-(?P<modmul>.+)_rsa-(?P<rsa>.+)\.prof$"
)
AVG_RE = re.compile(r"^Average\s+(?P<enc>[0-9.]+)\s+s\s+(?P<dec>[0-9.]+)\s+s")
ROUND_RE = re.compile(
    r"^Round\s+(?P<round>[0-9]+)\s+(?P<enc>[0-9.]+)\s+s\s+(?P<dec>[0-9.]+)\s+s"
)
STATUS_RE = re.compile(r"^(?P<kind>Encrypt|Decrypt)\s+:\s+\[(?P<status>PASS|FAIL)\]")
PROFILE_ROW_RE = re.compile(
    r"^\s*(?P<percent>[0-9.]+)\s+"
    r"(?P<cumulative>[0-9.]+)\s+"
    r"(?P<self>[0-9.]+)"
    r"(?:\s+(?P<calls>[0-9]+)\s+"
    r"(?P<self_per_call>[0-9.]+)\s+"
    r"(?P<total_per_call>[0-9.]+))?"
    r"\s+(?P<name>\S+)\s*$"
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract timing summaries from RSA run-all.sh output logs."
    )
    parser.add_argument(
        "out_dir",
        nargs="?",
        default="out",
        help="Directory containing *.log files generated by scripts/run-all.sh.",
    )
    parser.add_argument(
        "--csv",
        dest="csv_path",
        help="Optional path to write per-combination timing data as CSV.",
    )
    return parser.parse_args()


def parse_log(path):
    match = NAME_RE.match(path.name)
    if not match:
        return None

    entry = {
        "combination": path.stem,
        "mul": match.group("mul"),
        "modmul": match.group("modmul"),
        "rsa": match.group("rsa"),
        "encrypt_s": None,
        "decrypt_s": None,
        "rounds": 0,
        "encrypt_total_s": 0.0,
        "decrypt_total_s": 0.0,
        "total_s": 0.0,
        "encrypt_status": "",
        "decrypt_status": "",
    }

    for line in path.read_text(errors="replace").splitlines():
        round_time = ROUND_RE.match(line)
        if round_time:
            entry["rounds"] += 1
            entry["encrypt_total_s"] += float(round_time.group("enc"))
            entry["decrypt_total_s"] += float(round_time.group("dec"))
            continue

        avg = AVG_RE.match(line)
        if avg:
            entry["encrypt_s"] = float(avg.group("enc"))
            entry["decrypt_s"] = float(avg.group("dec"))
            continue

        status = STATUS_RE.match(line)
        if status:
            key = f"{status.group('kind').lower()}_status"
            entry[key] = status.group("status")

    if entry["encrypt_s"] is None or entry["decrypt_s"] is None:
        return None

    entry["total_s"] = entry["encrypt_total_s"] + entry["decrypt_total_s"]

    return entry


def parse_profile(path):
    match = PROFILE_NAME_RE.match(path.name)
    if not match:
        return None

    functions = []
    for line in path.read_text(errors="replace").splitlines():
        row = PROFILE_ROW_RE.match(line)
        if not row:
            continue

        functions.append(
            {
                "name": row.group("name"),
                "percent": float(row.group("percent")),
                "cumulative_s": float(row.group("cumulative")),
                "self_s": float(row.group("self")),
                "calls": int(row.group("calls")) if row.group("calls") else None,
                "self_per_call_s": (
                    float(row.group("self_per_call"))
                    if row.group("self_per_call")
                    else None
                ),
                "total_per_call_s": (
                    float(row.group("total_per_call"))
                    if row.group("total_per_call")
                    else None
                ),
            }
        )

    if not functions:
        return None

    top = max(functions, key=lambda item: item["self_s"])
    performance_test = next(
        (item for item in functions if item["name"] == "performance_test"), None
    )

    return {
        "combination": path.stem,
        "mul": match.group("mul"),
        "modmul": match.group("modmul"),
        "rsa": match.group("rsa"),
        "functions": functions,
        "function_count": len(functions),
        "sampled_s": max(item["cumulative_s"] for item in functions),
        "top_function": top["name"],
        "top_percent": top["percent"],
        "top_self_s": top["self_s"],
        "performance_test_s": (
            performance_test["total_per_call_s"] if performance_test else None
        ),
    }


def fmt_seconds(value):
    return f"{value:.6f}"


def fmt_optional_seconds(value):
    return fmt_seconds(value) if value is not None else ""


def italic(text):
    return f"\033[3m{text}\033[0m"


def bold(text):
    return f"\033[1m{text}\033[0m"


def print_table(headers, rows):
    widths = [len(header) for header in headers]
    for row in rows:
        for i, value in enumerate(row):
            widths[i] = max(widths[i], len(str(value)))

    print("  ".join(header.ljust(widths[i]) for i, header in enumerate(headers)))
    print("  ".join("-" * width for width in widths))
    for row in rows:
        print("  ".join(str(value).ljust(widths[i]) for i, value in enumerate(row)))


def aggregate(entries, module):
    groups = {}
    for entry in entries:
        key = entry[module]
        groups.setdefault(key, []).append(entry)

    rows = []
    for impl, values in sorted(groups.items()):
        enc = [item["encrypt_s"] for item in values]
        dec = [item["decrypt_s"] for item in values]
        rows.append(
            [
                module,
                impl,
                len(values),
                fmt_seconds(statistics.mean(enc)),
                fmt_seconds(min(enc)),
                fmt_seconds(max(enc)),
                fmt_seconds(statistics.mean(dec)),
                fmt_seconds(min(dec)),
                fmt_seconds(max(dec)),
            ]
        )
    return rows


def aggregate_profiles(profile_entries):
    functions = {}
    for entry in profile_entries:
        for function in entry["functions"]:
            name = function["name"]
            aggregate = functions.setdefault(
                name,
                {
                    "profiles": 0,
                    "self_s": 0.0,
                    "percent": 0.0,
                    "calls": 0,
                    "has_calls": False,
                },
            )
            aggregate["profiles"] += 1
            aggregate["self_s"] += function["self_s"]
            aggregate["percent"] += function["percent"]
            if function["calls"] is not None:
                aggregate["calls"] += function["calls"]
                aggregate["has_calls"] = True

    rows = []
    for name, values in sorted(
        functions.items(), key=lambda item: (-item[1]["self_s"], item[0])
    ):
        rows.append(
            [
                name,
                values["profiles"],
                fmt_seconds(values["self_s"]),
                fmt_seconds(values["percent"] / values["profiles"]),
                values["calls"] if values["has_calls"] else "",
            ]
        )
    return rows


def write_csv(path, entries):
    fields = [
        "combination",
        "mul",
        "modmul",
        "rsa",
        "encrypt_s",
        "decrypt_s",
        "rounds",
        "encrypt_total_s",
        "decrypt_total_s",
        "total_s",
        "encrypt_status",
        "decrypt_status",
    ]
    with Path(path).open("w", newline="") as out:
        writer = csv.DictWriter(out, fieldnames=fields)
        writer.writeheader()
        for entry in entries:
            writer.writerow({field: entry[field] for field in fields})


def main():
    args = parse_args()
    out_dir = Path(args.out_dir)
    entries = []
    profile_entries = []

    for path in sorted(out_dir.glob("*.log")):
        entry = parse_log(path)
        if entry:
            entries.append(entry)

    for path in sorted(out_dir.glob("*.prof")):
        entry = parse_profile(path)
        if entry:
            profile_entries.append(entry)

    if not entries and not profile_entries:
        raise SystemExit(f"No parseable benchmark logs or profiles found in {out_dir}")

    entries.sort(
        key=lambda item: (item["decrypt_s"], item["encrypt_s"], item["combination"])
    )
    profile_entries.sort(key=lambda item: (-item["sampled_s"], item["combination"]))

    print(f"Parsed {len(entries)} benchmark logs from {out_dir}")
    print(f"Parsed {len(profile_entries)} profile files from {out_dir}\n")

    if entries:
        total_rounds = sum(item["rounds"] for item in entries)
        total_enc = sum(item["encrypt_total_s"] for item in entries)
        total_dec = sum(item["decrypt_total_s"] for item in entries)
        print("\n" + bold(italic("Total performance test time")))
        print_table(
            ["benchmarks", "perf_tests", "enc_total_s", "dec_total_s", "total_s"],
            [
                [
                    len(entries),
                    total_rounds,
                    fmt_seconds(total_enc),
                    fmt_seconds(total_dec),
                    fmt_seconds(total_enc + total_dec),
                ]
            ],
        )

        print("\n" + bold(italic("Per-combination timings")))
        print_table(
            ["combination", "enc_s", "dec_s", "enc", "dec"],
            [
                [
                    item["combination"],
                    fmt_seconds(item["encrypt_s"]),
                    fmt_seconds(item["decrypt_s"]),
                    item["encrypt_status"],
                    item["decrypt_status"],
                ]
                for item in entries
            ],
        )

        print("\n" + bold(italic("Average by implementation")))
        aggregate_rows = []
        for module in ("mul", "modmul", "rsa"):
            aggregate_rows.extend(aggregate(entries, module))
        print_table(
            [
                "module",
                "implementation",
                "runs",
                "avg_enc_s",
                "min_enc_s",
                "max_enc_s",
                "avg_dec_s",
                "min_dec_s",
                "max_dec_s",
            ],
            aggregate_rows,
        )

        best_enc = min(entries, key=lambda item: item["encrypt_s"])
        best_dec = min(entries, key=lambda item: item["decrypt_s"])
        print("\n" + bold(italic("Best observed combinations")))
        print(
            f"Encrypt: {best_enc['combination']} ({fmt_seconds(best_enc['encrypt_s'])} s)"
        )
        print(
            f"Decrypt: {best_dec['combination']} ({fmt_seconds(best_dec['decrypt_s'])} s)"
        )

    if profile_entries:
        print("\n" + bold(italic("Per-profile summary")))
        print_table(
            [
                "combination",
                "sampled_s",
                "perf_test_s",
                "functions",
                "top_function",
                "top_self_s",
                "top_pct",
            ],
            [
                [
                    item["combination"],
                    fmt_seconds(item["sampled_s"]),
                    fmt_optional_seconds(item["performance_test_s"]),
                    item["function_count"],
                    item["top_function"],
                    fmt_seconds(item["top_self_s"]),
                    fmt_seconds(item["top_percent"]),
                ]
                for item in profile_entries
            ],
        )

        print("\n" + bold(italic("Top profile functions across all profiles")))
        print_table(
            ["function", "profiles", "self_total_s", "avg_pct", "calls"],
            aggregate_profiles(profile_entries)[:15],
        )

    if args.csv_path:
        write_csv(args.csv_path, entries)
        print(f"\nWrote CSV: {args.csv_path}")


if __name__ == "__main__":
    main()
