#!/usr/bin/env python3
import argparse
import csv
import re
import statistics
from pathlib import Path


NAME_RE = re.compile(r"^mul-(?P<mul>.+)_modmul-(?P<modmul>.+)_rsa-(?P<rsa>.+)\.log$")
AVG_RE = re.compile(r"^Average\s+(?P<enc>[0-9.]+)\s+s\s+(?P<dec>[0-9.]+)\s+s")
STATUS_RE = re.compile(r"^(?P<kind>Encrypt|Decrypt)\s+:\s+\[(?P<status>PASS|FAIL)\]")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract timing summaries from RSA run-all.sh output logs."
    )
    parser.add_argument(
        "out_dir",
        nargs="?",
        default="out",
        help="Directory containing *.log files generated by scripts/run-all.sh.",
    )
    parser.add_argument(
        "--csv",
        dest="csv_path",
        help="Optional path to write per-combination timing data as CSV.",
    )
    return parser.parse_args()


def parse_log(path):
    match = NAME_RE.match(path.name)
    if not match:
        return None

    entry = {
        "combination": path.stem,
        "mul": match.group("mul"),
        "modmul": match.group("modmul"),
        "rsa": match.group("rsa"),
        "encrypt_s": None,
        "decrypt_s": None,
        "encrypt_status": "",
        "decrypt_status": "",
    }

    for line in path.read_text(errors="replace").splitlines():
        avg = AVG_RE.match(line)
        if avg:
            entry["encrypt_s"] = float(avg.group("enc"))
            entry["decrypt_s"] = float(avg.group("dec"))
            continue

        status = STATUS_RE.match(line)
        if status:
            key = f"{status.group('kind').lower()}_status"
            entry[key] = status.group("status")

    if entry["encrypt_s"] is None or entry["decrypt_s"] is None:
        return None

    return entry


def fmt_seconds(value):
    return f"{value:.6f}"


def print_table(headers, rows):
    widths = [len(header) for header in headers]
    for row in rows:
        for i, value in enumerate(row):
            widths[i] = max(widths[i], len(str(value)))

    print("  ".join(header.ljust(widths[i]) for i, header in enumerate(headers)))
    print("  ".join("-" * width for width in widths))
    for row in rows:
        print("  ".join(str(value).ljust(widths[i]) for i, value in enumerate(row)))


def aggregate(entries, module):
    groups = {}
    for entry in entries:
        key = entry[module]
        groups.setdefault(key, []).append(entry)

    rows = []
    for impl, values in sorted(groups.items()):
        enc = [item["encrypt_s"] for item in values]
        dec = [item["decrypt_s"] for item in values]
        rows.append(
            [
                module,
                impl,
                len(values),
                fmt_seconds(statistics.mean(enc)),
                fmt_seconds(min(enc)),
                fmt_seconds(max(enc)),
                fmt_seconds(statistics.mean(dec)),
                fmt_seconds(min(dec)),
                fmt_seconds(max(dec)),
            ]
        )
    return rows


def write_csv(path, entries):
    fields = [
        "combination",
        "mul",
        "modmul",
        "rsa",
        "encrypt_s",
        "decrypt_s",
        "encrypt_status",
        "decrypt_status",
    ]
    with Path(path).open("w", newline="") as out:
        writer = csv.DictWriter(out, fieldnames=fields)
        writer.writeheader()
        for entry in entries:
            writer.writerow({field: entry[field] for field in fields})


def main():
    args = parse_args()
    out_dir = Path(args.out_dir)
    entries = []

    for path in sorted(out_dir.glob("*.log")):
        entry = parse_log(path)
        if entry:
            entries.append(entry)

    if not entries:
        raise SystemExit(f"No parseable benchmark logs found in {out_dir}")

    entries.sort(key=lambda item: (item["decrypt_s"], item["encrypt_s"], item["combination"]))

    print(f"Parsed {len(entries)} benchmark logs from {out_dir}\n")

    print("Per-combination timings")
    print_table(
        ["combination", "enc_s", "dec_s", "enc", "dec"],
        [
            [
                item["combination"],
                fmt_seconds(item["encrypt_s"]),
                fmt_seconds(item["decrypt_s"]),
                item["encrypt_status"],
                item["decrypt_status"],
            ]
            for item in entries
        ],
    )

    print("\nAverage by implementation")
    aggregate_rows = []
    for module in ("mul", "modmul", "rsa"):
        aggregate_rows.extend(aggregate(entries, module))
    print_table(
        ["module", "implementation", "runs", "avg_enc_s", "min_enc_s", "max_enc_s", "avg_dec_s", "min_dec_s", "max_dec_s"],
        aggregate_rows,
    )

    best_enc = min(entries, key=lambda item: item["encrypt_s"])
    best_dec = min(entries, key=lambda item: item["decrypt_s"])
    print("\nBest observed combinations")
    print(f"Encrypt: {best_enc['combination']} ({fmt_seconds(best_enc['encrypt_s'])} s)")
    print(f"Decrypt: {best_dec['combination']} ({fmt_seconds(best_dec['decrypt_s'])} s)")

    if args.csv_path:
        write_csv(args.csv_path, entries)
        print(f"\nWrote CSV: {args.csv_path}")


if __name__ == "__main__":
    main()
